"""
Pydantic models for request / response validation.
"""

from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    """Body sent by the frontend to the /ask endpoint."""
    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        examples=["What career suits someone who loves math and coding?"],
        description="The user's career-related question.",
    )


class AskResponse(BaseModel):
    """Response returned by the /ask endpoint."""
    answer: str = Field(
        ...,
        description="Career guidance generated by Claude AI.",
    )
